name: Issue Auto Comment

# Created by @smog-root

on:
  issues:
    types: [opened, closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add a comment when an issue is closed
        if: github.event.action == 'closed'
        uses: actions-ecosystem/action-create-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          body: " ✅ This issue has been successfully closed. Thank you for your contribution and helping us improve the project! If you have any more ideas or run into other issues, feel free to open a new one. Happy coding! 🚀"