name: 🐞 Bug Report
---
description: Report a bug found in the MLFusionLab source code
labels: ["bug", "GSSoC24 Extd."]
---

### Description
A brief description of the question or issue, also include what you tried and what didn't work

### Screenshots
Please add screenshots if applicable (recommended)

### Additional information
Is there anything else we should know about this bug?

### What browser are you seeing the problem on?
- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist
- [ ] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [ ] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I want to work on this issue. (optional)

---

You can also join the Discord community [here]( https://discord.gg/FZxBRpTEeH).
